<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="9.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.16" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryProAPI.Application\InventoryProAPI.Application.csproj" />
    <ProjectReference Include="..\InventoryProAPI.Domain\InventoryProAPI.Domain.csproj" />
  </ItemGroup>

</Project>
